name: Some

on:
  workflow_dispatch:
  
jobs: 
  change: 
    runs-on:  ubuntu-latest
    steps:
      - name: Test
        run:  git clone https://github.com/Ramudu-stockone/ttest.git
          
      
